spring.application.name=website-controller
server.port=8090
server.error.include-message=always
spring.thymeleaf.cache=false
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=10MB

# Gateway Microservice URLs
services.gateway.url=http://localhost:8091/api
services.auth.url=${services.gateway.url}/auth
services.profile.url=${services.gateway.url}/profiles
services.product.url=${services.gateway.url}/products
services.cart.url=${services.gateway.url}/cart
services.order.url=${services.gateway.url}/orders
services.payment.url=${services.gateway.url}/payments
services.delivery.url=${services.gateway.url}/delivery
services.wallet.url=${services.gateway.url}/wallet
services.notification.url=${services.gateway.url}/notifications

# Default Admin Credentials
app.admin.name=System Admin
app.admin.email=admin@eshoppingzone.local
app.admin.password=admin123
